%%{init: {'theme': 'dark', 'themeVariables': { 'background': '#000000', 'lineColor': '#ffffff'}, 'flowchart': {'curve': 'step', 'defaultRenderer': 'elk'}}}%%
flowchart LR
    %% Entities
    S[Student]
    P[Instructor]
    C[Course]

    %% Entity-Relationship Connections
    S ---|"N"| Enroll{Enrolls}
    S ---|"N"| Eval{Evaluates}
    Enroll ---|"M"| C
    Eval ---|"M"| P
    Eval ---|"1"| C
    P ---|"1"| Teach{Teaches}
    Teach ---|"N"| C

    %% Attributes Student
    S_User([Username]) --- S
    S_Name(["(Full Name)"]) --- S
    S_FName([First Name]) --- S_Name
    S_LName([Last Name]) --- S_Name
    S_Pass([Password]) --- S
    S_Email([Email]) --- S
    S_AM(["<u>Registration Number (AM)</u>"]) --- S

    %% Attributes Instructor/Professor
    P --- P_AM(["<u>Registration Number (AM)</u>"])
    P --- P_User([Username])
    P --- P_Name(["(Full Name)"])
    P_Name --- P_FName([First Name])
    P_Name --- P_LName([Last Name])
    P --- P_Email([Email])
    P --- P_Spec([Specialization])
    P --- P_Pass([Password])

    %% Attributes Course
    C --- C_Title([Title])
    C --- C_Code(["<u>Course Code</u>"])
    C --- C_Desc([Description])
    C --- C_Cat([Category])

    %% Attributes Relationships
    Eval --- Eval_Grade([Rating])
    Eval --- Eval_Comments([Comments])
    Enroll --- Enroll_Date([Start Date])

    %% Apply Classes to Entities and Relationships (Roots)
    class S,P,C,Eval,Enroll,Teach rootNode;

    %% Apply Classes to Attributes (Branches)
    class S_User,S_Name,S_FName,S_LName,S_Pass,S_Email,S_AM,P_AM,P_User,P_Name,P_FName,P_LName,P_Email,P_Pass,P_Spec,C_Title,C_Code,C_Desc,C_Cat,Eval_Grade,Eval_Comments,Enroll_Date branchNode;

    %% Styling Definitions
    classDef rootNode fill:#0055ff,stroke:#fff,stroke-width:2px,color:#fff;
    classDef branchNode fill:#ffcc00,stroke:#333,stroke-width:2px,color:#000;