PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS STUDENT (
    AM VARCHAR(20) PRIMARY KEY,
    Password VARCHAR(255) NOT NULL,
    Username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTRUCTOR (
    AM VARCHAR(20) PRIMARY KEY,
    Password VARCHAR(255) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    Specialization VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS COURSE (
    C_Code VARCHAR(20) PRIMARY KEY,
    AM_Instructor VARCHAR(20),
    Title VARCHAR(100) NOT NULL,
    Description TEXT,
    Category VARCHAR(50),
    FOREIGN KEY (AM_Instructor) REFERENCES INSTRUCTOR(AM)
);

CREATE TABLE IF NOT EXISTS ENROLLMENT (
    AM_Student VARCHAR(20),
    C_Code VARCHAR(20),
    StartDate DATE NOT NULL,
    PRIMARY KEY (AM_Student, C_Code),
    FOREIGN KEY (AM_Student) REFERENCES STUDENT(AM),
    FOREIGN KEY (C_Code) REFERENCES COURSE(C_Code)
);

CREATE TABLE IF NOT EXISTS EVALUATION (
    AM_Instructor VARCHAR(20),
    AM_Student VARCHAR(20),
    C_Code VARCHAR(20),
    Rating INTEGER,
    Comments TEXT,
    PRIMARY KEY (AM_Instructor, AM_Student, C_Code),
    FOREIGN KEY (AM_Instructor) REFERENCES INSTRUCTOR(AM),
    FOREIGN KEY (AM_Student) REFERENCES STUDENT(AM),
    FOREIGN KEY (C_Code) REFERENCES COURSE(C_Code)
);